# Generated by Django 5.0.6 on 2024-05-09 10:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Online Service', 'Online Service'), ('Travel', 'Travel'), ('Food', 'Food'), ('Rent', 'Rent'), ('Others', 'Others')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, max_length=10)),
                ('description', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
